Add loading

diff --git a/.github/workflows/releases.yml b/.github/workflows/releases.yml
--- a/.github/workflows/releases.yml
+++ b/.github/workflows/releases.yml
@@ -1,118 +1,90 @@
-name: "Build IPK"
+name: Build IPK
+
 on:
-  repository_dispatch:
-  workflow_dispatch: {}
   push:
-    branches:
-      - 'master'
     paths:
-      - 'luci-app-ipinfo/Makefile'
-env:
-  TZ: Asia/Jakarta
+      - 'Makefile'
+  workflow_dispatch:
 
 jobs:
-  job_check:
-    if: github.repository == ${{ github.repository }}
-    name: Check Version
-    runs-on: ubuntu-22.04
-    outputs:
-      version: ${{ steps.check_version.outputs.latest_version }}
-      has_update: ${{ steps.check_version.outputs.has_update }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@main
-        with:
-          fetch-depth: 0
-          ref: 'master'
-
-      - name: Check version
-        id: check_version
-        env:
-          url_release: https://api.github.com/repos/${{ github.repository }}/releases/latest
-        run: |
-          latest_version=$(grep -oP 'PKG_VERSION:=\K.*' Makefile | sed 's/^/v/')
-          latest_release=$(wget -qO- -t1 -T2 ${{env.url_release}} | awk -F '"' '/tag_name/{print $4}')
-          has_update=$([ "${latest_version}" != "${latest_release}" ] && echo true || echo false)
-          echo "latest_version=${latest_version}" >> $GITHUB_OUTPUT
-          echo "has_update=${has_update}" >> $GITHUB_OUTPUT
-          echo "latest_version: ${latest_version}"
-          echo "latest_release: ${latest_release}"
-          echo "has_update: ${has_update}"
-      - name: Generate new tag & release
-        if: steps.check_version.outputs.has_update == 'true'
-        uses: softprops/action-gh-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          name: luci-app-ipinfo
-          tag_name: ${{steps.check_version.outputs.latest_version}}
-
-
-  job_build:
-    name: Build OpenWRT
-    needs: job_check
-    if: needs.job_check.outputs.has_update == 'true'
+  build:
     runs-on: ubuntu-22.04
     steps:
-      - name: Install packages
-        run: |
-          echo "Install packages"
-          sudo -E apt-get -qq update
-          sudo -E apt-get -qq install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
-          sudo -E apt-get -qq autoremove --purge
-          sudo -E apt-get -qq clean
-      - name: Cache openwrt SDK
-        id: cache-sdk
-        uses: actions/cache@v3
-        with:
-          path: sdk
-          key: openwrt-sdk-23.05-x86-64
+      - uses: actions/checkout@v4
 
-      - name: Initialization environment
-        if: steps.cache-sdk.outputs.cache-hit != 'true'
-        env:
-          url_sdk: https://archive.openwrt.org/releases/23.05.2/targets/x86/64/openwrt-sdk-23.05.2-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
+      - name: Siapkan OpenWrt SDK
         run: |
-          wget ${{ env.url_sdk }}
-          file_name=$(echo ${{env.url_sdk}} | awk -F/ '{print $NF}')
-          mkdir sdk && tar -xJf $file_name -C ./sdk --strip-components=1
-          cd sdk  
-          echo "src-git base https://github.com/openwrt/openwrt.git;openwrt-23.05" > feeds.conf
-          echo "src-git-full packages https://github.com/openwrt/packages.git;openwrt-23.05" >> feeds.conf
-          echo "src-git-full luci https://git.openwrt.org/project/luci.git;openwrt-23.05" >> feeds.conf
-          echo "src-git-full routing https://git.openwrt.org/feed/routing.git;openwrt-23.05"  >> feeds.conf
-          git clone -b master https://github.com/${{ github.repository }}.git package/downloads/luci-app-ipinfo
+          sudo apt update
+          sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget tar -y
+          wget https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
+          tar xJf openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
+          mv openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64 openwrt-sdk
+
+      - name: Perbarui dan pasang feeds
+        run: |
+          cd openwrt-sdk
           ./scripts/feeds update -a
-          echo "CONFIG_PACKAGE_luci-app-ipinfo=m" > .config
-          ./scripts/feeds install -d n luci-app-ipinfo
-          make download -j8
-      - name: Configure IPK
+          ./scripts/feeds install -a
+
+      - name: Dapatkan Versi dan Nama Paket
+        id: get_info
         run: |
-          cd sdk
-          ./scripts/feeds install luci-app-ipinfo
-          echo "CONFIG_ALL_NONSHARED=n" > .config
-          echo "CONFIG_ALL_KMODS=n" >> .config
-          echo "CONFIG_ALL=n" >> .config
-          echo "CONFIG_AUTOREMOVE=n" >> .config
-          echo "CONFIG_LUCI_LANG_zh_Hans=n" >> .config
-          echo "CONFIG_PACKAGE_luci-app-ipinfo=m" >> .config
-          make defconfig
-      - name: Compile IPK
-        id: compile
+          echo "version=$(grep 'PKG_VERSION:=' Makefile | awk -F '=' '{print $2}' | tr -d ' ')" >> $GITHUB_OUTPUT
+          echo "PKG_NAME=$(basename ${{ github.repository }})" >> $GITHUB_OUTPUT
+
+      - name: Siapkan Paket
         run: |
-          cd sdk
-          echo "make package/luci-app-ipinfo/{clean,compile} -j$(nproc)"
-          make package/luci-app-ipinfo/{clean,compile} -j$(nproc)
-          mv bin/packages/x86_64/base/ ../
-          rm .config .config.old
-          cd ..
-          echo "status=success" >> $GITHUB_OUTPUT
-          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
-      - name: Upload IPK to release
-        uses: softprops/action-gh-release@v1
-        if: steps.compile.outputs.status == 'success'
+          cd openwrt-sdk
+          git clone -q https://github.com/${{ github.repository }} package/${{ steps.get_info.outputs.PKG_NAME }}
+
+      - name: Build Paket
+        id: build
+        run: |
+          cd openwrt-sdk && make defconfig
+          sed -i 's/CONFIG_LUCI_SRCDIET=y/# CONFIG_LUCI_SRCDIET is not set/' .config
+          sed -i 's/CONFIG_LUCI_JSMIN=y/# CONFIG_LUCI_JSMIN is not set/' .config
+          sed -i 's/CONFIG_LUCI_CSSTIDY=y/# CONFIG_LUCI_CSSTIDY is not set/' .config
+          sed -i 's/# CONFIG_NO_STRIP is not set/CONFIG_NO_STRIP=y/' .config
+          sed -i 's/CONFIG_USE_STRIP=y/# CONFIG_USE_STRIP is not set/' .config
+          sed -i 's/CONFIG_USE_SSTRIP=y/# CONFIG_USE_SSTRIP is not set/' .config
+          make package/${{ steps.get_info.outputs.PKG_NAME }}/compile V=s -j$(nproc) || echo "BUILD_FAILED=true" >> $GITHUB_ENV
+          if [ "${{ env.BUILD_FAILED }}" != "true" ]; then
+            mv bin/packages/x86_64/base/${{ steps.get_info.outputs.PKG_NAME }}*.ipk ../${{ steps.get_info.outputs.PKG_NAME }}-${{ steps.get_info.outputs.version }}_beta_all.ipk
+          fi
+
+      - name: Buat Rilis
+        if: env.BUILD_FAILED != 'true'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: ${{needs.job_check.outputs.version}}
-          files: ${{ env.FIRMWARE }}/base/luci-app-*.ipk
+        run: |
+          release_date=$(date +'%y%m%d')
+          release_name="${{ steps.get_info.outputs.PKG_NAME }}-${release_date}"
+          release_tag="${{ steps.get_info.outputs.version }}"
+          release_body="# 🚀 ${{ steps.get_info.outputs.PKG_NAME }} for OpenWRT
+
+          ## 📦 Release Version: \`${{ steps.get_info.outputs.version }}\` all
+
+          ### 🌟 Features:
+            - Internet connect or disconnect
+            - IP & ISP
+            - Organization & Country name
+            - Country & city
+            - Time zone
+            - Latitude & Longitude
+
+          > 🔔 Always ensure you're using the latest version for the best performance!
+
+          *Thank you for using ${{ steps.get_info.outputs.PKG_NAME }}!* 🙏"
+
+          gh release create "$release_tag" \
+            --title "$release_name" \
+            --notes "$release_body" \
+            --generate-notes=false
+
+      - name: Unggah IPK
+        if: env.BUILD_FAILED != 'true'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          gh release upload ${{ steps.get_info.outputs.version }} \
+            ./${{ steps.get_info.outputs.PKG_NAME }}-${{ steps.get_info.outputs.version }}_all.ipk
